<div class="bg-white dark:bg-gray-800 p-6 rounded-lg shadow border border-gray-100" x-data="{ track: {{ $product->track_stock ? 'true' : 'false' }} }">
    <div class="flex items-center gap-3 mb-6">
        <div class="w-8 h-8 rounded-full bg-red-100 flex items-center justify-center">
            <svg class="w-4 h-4 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"></path>
            </svg>
        </div>
        <h3 class="text-lg font-bold text-gray-900">{{ __('Inventory') }}</h3>
    </div>

    <div class="space-y-6">
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">SKU (Auto-generated By System)</label>
            <input type="text" name="sku" x-model="sku" placeholder="Auto-generated By System"
                disabled
                class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 py-3 px-4 border bg-gray-100 cursor-not-allowed">
        </div>

        <div class="bg-gray-50 p-4 rounded-lg">
            <label class="flex items-center gap-3 cursor-pointer group">
                <input type="checkbox" x-model="track" @input.debounce.1000ms="triggerAutosave()"
                        class="w-4 h-4 text-indigo-600 border-gray-300 rounded focus:ring-indigo-500">
                <div>
                    <span class="font-medium text-gray-900">Track quantity</span>
                    <p class="text-sm text-gray-500">Enable stock management for this product</p>
                </div>
            </label>
        </div>

        <template x-if="track">
            <div class="bg-white p-4 rounded-lg border border-gray-200">
                <label class="block text-sm font-medium text-gray-700 mb-2">Stock Quantity</label>
                <input type="number" name="stock_quantity" value="{{ $product->stock_quantity ?? 0 }}" @input.debounce.1000ms="triggerAutosave()"
                    class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 py-2 px-3 border">
                <p class="text-xs text-gray-500 mt-1">Current quantity available for sale</p>
            </div>
        </template>
    </div>
</div>